### ISSUE TITLE
Thunderbird periodically reloads IMAP account when running sync-engine against it 

### ISSUE THREAD

**Issue by arthurlutz** [nylas/sync-engine#229]
While trying out sync-engine, my thunderbird that is pointing to the same IMAP server gets disconnected and re-downloads the inbox and the headers. Does sync-engine change things that could provoke this behaviour ? So far I have not made any modifications from an N1 client (still working on getting it to work). 

Am using thunderbird 38.3.0 from ubuntu. And sync-engine from git in an vagrant setup.

I can debug further if pointed in the right direction.

**Comment by khamidou** [comment]
Hi Arthur,

This is really weird. Can you give us more details about your IMAP server? Is it Gmail? A generic IMAP server like Dovecot or Cyrus? Is there a connection limit to the server?

I'm asking because the sync engine downloads messages in parallel --- it sometimes uses ~ 3 simultaneous connections to the same server. It's possible that the server decided there were too many connections to the same inbox and decided to kill the connection thunderbird held.

Also, it would be super helpful if you could send us the sync-engine logs. You can send them by email at karim@nylas.com if you're not comfortable sharing them publicly.

regards,

Karim

**Comment by grinich** [comment]
Stale.
