### ISSUE TITLE
How To Install sync-engine Without Using VM

### ISSUE THREAD

**Issue by Majal** [nylas/sync-engine#243]
**Question:** Can we install `sync-engine` without the need to run inside VirtualBox / Vagrant?

**Reasons:**

1. Just the VM itself takes extra resources like disk space, RAM, and CPU.
VirtualBox will allocate a full 1GB of RAM to the VM -- and `sync-engine` may not need that much, yet that is the drawback on running inside a virtual environment with allocated RAM. (+VB's extra RAM overhead)

2. Some of us simply need an email client with the capacity to access our emails **offline**. Some of us may want an email client that is **responsive to search**. Both (apparently) are thus addressed by a locally installed `sync-engine`. But with the current overhead, it's a little difficult to justify installing it on a laptop to get the aforementioned benefits... ;-)

Thanks for considering!

**Comment by andysaini** [comment]
+1, running sync-engine inside vm seems like a waste of resources..

**Comment by grinich** [comment]
If you're running Debian 7 (like Ubuntu 12.04) you can just install directly by running `setup.sh`. This is what we deploy to. Most of our developers are on Mac OS, so we run it within a VM to mirror production, and even our folks on Linux choose to still use a VM for isolation with the host OS.

I think most modern VM managers won't allocate the entire 1GB upon boot, and instead just use it as a maximum. If you're already running Linux, I think the overhead of VirtualBox is pretty minimal since it doesn't need to do much translation.

It's totally possible to run the entire stack yourself, but N1 isn't optimized for this. We made specific choices when developing this platform that pushed a lot of the "heavy lifting" to server-side infrastructure, similar to mobile apps like Mailbox and Acompli. It has a lot of benefits, but certainly also some constraints compared to existing apps like Thunderbird or Mac Mail.

As far as search goes, the sync engine just proxies requests to the backend system, so the speedup probably won't be huge. (Eventually we're hoping to build our own faster search system.)

**Comment by biji** [comment]
Check out this wiki:
https://github.com/nylas/sync-engine/wiki/Running-under-systemd-nspawn
