### ISSUE TITLE
Limitations - custom environment - sync engine + N1 client

### ISSUE THREAD

**Issue by bambita** [nylas/sync-engine#304]
Hello,

After few minutes of usage I found that I can not use:
- snooze
- calendar
- send later
- tracking

![image 420](https://cloud.githubusercontent.com/assets/16983664/15632548/d3c15a8e-25a6-11e6-9b85-02d8246363a6.png)

All features above are available only on hosted/commercial server. So I do not see any practical reason of using nylas on own environment since there is no functionality other than sending/receiving emails.

What are all other limitations of running sync-engine on own server and using N1 client? Is it published somewhere?

Thanks.

**Comment by khamidou** [comment]
Hi!

To give a bit more context about this, we implemented send later and snooze as a separate service because we wanted to do the right thing (i.e: emails should be unsnoozed even if you're not using N1 when it happens). 

The hosted sync-engine uses the same source code as the open source version, apart from Exchange support.

Cheers,

k

**Comment by bambita** [comment]
Hello,

thank you for your reply.

Now I am more confused. You said:

> The hosted sync-engine uses the same source code as the open source version, apart from Exchange support.

Is there any of following feature available in custom (self-hosted) environment?

-     snooze
-     calendar
-     send later
-     tracking

If yes, how can I set it up?

Thank you in advance.
