### ISSUE TITLE
Matching localized folder names does not update role for clients

### ISSUE THREAD

**Issue by happydemic** [nylas/sync-engine#377]
Continued from nylas/N1#1457 - thanks @hallamoore 

**Bug**: Nylas does not always correctly identify special folders with variant but predictable names. The logic to match localised folder names at [_guess_role()](https://github.com/nylas/sync-engine/blob/master/inbox/crispin.py#L533) is applied by crispin, but the updated folder roles may not be available to clients via the API.

**Version**: [92313a](https://github.com/nylas/sync-engine/commit/92313a289abe74cdf8f1e014df8d17620d146cad)

The "Deleted Items" folder is still not being processed correctly - sorry! 

"Deleted Items" is correctly identified as 'trash' by crispin, as can be seen from inbox-console:

```
In [1]: crispin_client.folder_names()
Out[1]: defaultdict(<type 'list'>, {'drafts': [u'Drafts'], None: [u'N1-Snoozed', u'Outbox', u'Sync Issues'], 'spam': [u'Junk E-Mail'], 'inbox': [u'INBOX'], 'trash': [u'Deleted Items'], 'archive': [u'Archive'], 'sent': [u'Sent Items']})
```

**BUT** "Deleted Items" is still not identified as "trash" at the folders endpoint (or on N1); the "name" property appears as "null" instead: `{
        "account_id": [xxxxx],
        "display_name": "Deleted Items",
        "id": [xxxxx],
        "name": null,
        "object": "folder"
    },`

Interestingly, the mapping for "spam" **_is**_ being passed correctly to the folders endpoint, and on to N1. (I could not test this before [92313a](https://github.com/nylas/sync-engine/commit/92313a289abe74cdf8f1e014df8d17620d146cad) because my account requires a localised mapping which was first added to folder_edge_cases in that commit - thanks for adding the British English versions.)

**Comment by happydemic** [comment]
@hallamoore , I got a chance to look at this just now. The conditional at [line 108](https://github.com/nylas/sync-engine/blob/master/inbox/mailsync/backends/imap/monitor.py#108) is not working as expected. 

Omitting the conditional resolves the bug. The conditional has no other purpose except to assign the variable, so omitting it has no wider logical consequences. I'm not sure if the overhead is higher with or without the conditional (I don't really use python).

**Comment by hallamoore** [comment]
@happydemic Ah, I should have realized this would happen. The fix will probably be just to change that conditional to ```if folder.canonical_name != raw_folder.role or folder.category.name != raw_folder.role:``` Here's a more detailed explanation about what's going on, if you're interested:

Basically, the underlying issue this entire time has been that we have to deal with the notion of not only a Folder, but also of a Category (which is our generic representation for either a Folder or a Gmail-style Label). This processing code was updating the Folder roles, but not the roles for the corresponding Category objects. We look at the Categories when actually trying to find specific roles, so since the Category wasn't updated properly, we weren't finding the right Folders. With the [92313a](https://github.com/nylas/sync-engine/commit/92313a289abe74cdf8f1e014df8d17620d146cad) commit, we overrode the setter on the Folder to also update the proper attribute on the Category object. However, that conditional at line 108 makes it so we only invoke the setter if your Folder role is out of sync, and the issue is that your Folder role is fine while your Category role is out of sync. Changing the conditional to  ```if folder.canonical_name != raw_folder.role or folder.category.name != raw_folder.role:``` will then invoke the setter if either one is out of sync.

(I also don't think we want to just always invoke the setter, since it would require two writes to the database for every folder, every time we synced them. That probably wouldn't be a huge load for your local sync engine, but would add up quickly on our production sync engine. Thanks for the suggestion though!)

**Comment by happydemic** [comment]
I knew there had to be an explanation! Makes sense, and thanks for the lesson. :)

**Comment by grinich** [comment]
Closing due to stale and can't reproduce. -- Please try the new Nylas Mail!
