### ISSUE TITLE
/files/:id/download end-point is not working, with 'View function did not return a response' error.

### ISSUE THREAD

**Issue by Analect** [nylas/sync-engine#398]
Version 0.4.51 ... using a self-hosted sync-engine using the nhurel/nylas-sync-engine set-up.

If I use the /files/id endpoint, it works fine.
```
curl -H 'Authorization: Basic N3U0cTNtMG9hdW5oamR2MGxxxxxxxxxxxxxxhqZHYwZHJlNm5iaTln' http://my-server-ip:5555/files/10hr2szqipu4cnetw1i21e6ma
{
    "account_id": "xxxxx7u4nbi9g",
    "content_id": "<xxxxx@github-fe127-cp1-prd.iad.github.net.mail>",
    "content_type": "application/pdf",
    "filename": "github-xxxxxxx-xxxxxxx-2016-08-08.pdf",
    "id": "10hr2szqipu4cnetw1i21e6ma",
    "message_ids": [
        "3edjeebfckpvc4ksflh15r727"
    ],
    "object": "file",
    "size": 53896
}
```
If I then try to download the file, by appending `/download` to the end-point above, it fails with a 500 error.
```
curl --verbose --include -H 'Authorization: Basic N3U0cTNtMG9hdW5oxxxxxxxxxxxxxxxxJlNm5iaTln' http://my-server-ip:5555/files/10hr2szqipu4cnetw1i21e6ma/download
* Hostname was NOT found in DNS cache
*   Trying <my-server-ip>...
* Connected to my-server-ip port 5555 (#0)
> GET /files/10hr2szqipu4cnetw1i21e6ma/download HTTP/1.1
> User-Agent: curl/7.35.0
> Host: my-server-ip:5555
> Accept: */*
> Authorization: Basic N3U0cTNtMG9hdW5oaxxxxxxxxxxxxxxwZHJlNm5iaTln
> 
< HTTP/1.1 500 INTERNAL SERVER ERROR
HTTP/1.1 500 INTERNAL SERVER ERROR
< Content-Type: application/json
Content-Type: application/json
< Content-Length: 81
Content-Length: 81
< Date: Mon, 19 Sep 2016 10:00:16 GMT
Date: Mon, 19 Sep 2016 10:00:16 GMT

< 
{
  "message": "View function did not return a response",
  "type": "api_error"
* Connection #0 to host my-server-ip left intact
```

The 'View function did not return a response' suggests a possible Flask-related error, where there's a missing 'return', as per this SO [answer](http://stackoverflow.com/questions/18211942/flask-view-return-error-view-function-did-not-return-a-response). I can see from [here](https://github.com/nylas/sync-engine/blob/987e975f22d9f0b8e0d3b48b2b4da4a0a670981c/inbox/api/ns_api.py#L1179-L1228) that there's a 'return' at the end, so the problem isn't obvious to me, but might be to experts your end.

**Comment by pfista** [comment]
It's possible that the file you're trying to download is no longer in your VM, or was never there to begin with. In the self hosted sync engine we store all raw file contents in `/var/lib/inboxapp` across a sharded directory structure where each subdir is one letter popped off the front of the hash of the file. We do this for about 6 levels. 

For example, if your file hash is `07c8ab0d47397be345b5de93a99349e6200846815e74b4dfb5fe45638f17dff0`, it would be stored here: `/var/lib/inboxapp/0/7/c/8/a/b/07c8ab0d47397be345b5de93a99349e6200846815e74b4dfb5fe45638f17dff0`.

My assumption is that there are issues with the docker container and storing files at `/var/lib/inboxapp`, and we unfortunately do not support docker containers right now. Can you test this inside a regular VM and see if the issue still persists? 

I can reproduce this response on my end by setting `f.data` to `None` [on this line](https://github.com/nylas/sync-engine/blob/91e3a8bff6ef0656eca9e356c07963c8b238d876/inbox/api/ns_api.py#L1214) which is why I believe the file is missing.

**Comment by Analect** [comment]
@pfista ... thanks for helping me to figure this out. I think you were right, in terms of the file no longer being where it should have been.  In the dockerized version, it seems there needs to be a `volume` flag to persist the `\var\lib\inboxapp` folder to the host or somewhere external to the container, since, from what I can tell, the wisdom up to now has been that the sync-engine container is disposable, particularly when upgrading to the latest version.

I don't suppose there's any mechanism in place to re-fetch attachments? ... or is the only solution to start from scratch with a clean system. I note from other issues on here that deleting and re-adding an account, on the self-hosted version at least, is not working well (ends up in a duplicated account).

**Comment by pfista** [comment]
I'd recommend starting with an empty database to ensure account data isn't left behind, and then add your account again once you're able to persist files with your setup. It'd be awesome if you could let @nhurel know about this issue!

**Comment by khamidou** [comment]
Looks like @nhurel already fixed it: https://github.com/nhurel/nylas-sync-engine/commit/b9324d78915d37acbc2f5bba22ff9ea9c69d533c !
