### ISSUE TITLE
"No name provided"

### ISSUE THREAD

**Issue by josephh11** [nylas/sync-engine#407]
When setting up accounts they are set up without a "Full name".

In N1 the client says "No name provided".

Any way to change to add name, way to edit database?

**Comment by andrey-str** [comment]
Same question here. N1 offers to 'edit' account, but for me it doesn't work, because it can't authorize with mail server for some reason(probably because SMTP uses STARTTLS, and IMAP works over SSL, but there is no option for STARTTLS on setup screen; though I am not quite sure in this).

I believe there is should be a way to edit this information on the server side.

**Comment by mayrmartin** [comment]
Same question here.

**Comment by grinich** [comment]
Closing due to stale and can't reproduce. Try this on the new Nylas Mail app?
